import { ValorNutricional } from "./interfaces/valorNutricional.interface";

export const baseForm: ValorNutricional[] = [
    {
      label: "Valor energético",
      bold: true,
      order: 2,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "kcal",
      unidadCDR: "kcal",
    },
    {
      label: "Grasas",
      bold: true,
      order: 3,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "de las cuales saturadas",
      bold: false,
      order: 4,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "Carbohidratos",
      bold: true,
      order: 5,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "de los cuales azúcares",
      bold: false,
      order: 6,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "Fibra",
      bold: true,
      order: 7,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "Proteína",
      bold: true,
      order: 8,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
    {
      label: "Sal",
      bold: true,
      order: 9,
      valorPorcion: "",
      valorCDR: "",
      unidadPorcion: "g",
      unidadCDR: "g",
    },
  ];
  